# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=140)),
                ('status', models.CharField(choices=[('O', 'Open'), ('IP', 'In progress'), ('C', 'Close')], default='O', max_length=10)),
                ('close_date', models.DateField(blank=True, null=True, verbose_name='Close Date')),
                ('created_date', models.DateField(auto_now_add=True, null=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='agents.Agent')),
            ],
        ),
    ]
