# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='response',
            field=models.TextField(blank=True, max_length=254, null=True),
        ),
    ]
