# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tickets', '0001_initial'),
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='tickets',
            field=models.ManyToManyField(blank=True, related_name='agents', to='tickets.Ticket'),
        ),
    ]
