# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 23:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0002_agent_tickets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='tickets',
        ),
        migrations.DeleteModel(
            name='Agent',
        ),
    ]
