# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 21:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('username', models.CharField(default='', max_length=12, primary_key=True, serialize=False)),
                ('full_name', models.CharField(blank=True, max_length=140)),
                ('email', models.CharField(blank=True, max_length=140)),
                ('password', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
